name: Update Processing Status

on:
  schedule:
    - cron: '*/1 * * * *' # 1분마다 실행

# on:
#   schedule:
#     - cron: '0 15 * * *' # UTC(협정 세계시) + 9시간 = 한국 시간대 
#                          # 자정에 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run code to update processing status
      run: node index.js # 여기에 자신의 스크립트 파일 이름을 입력하세요
      env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        HELPDESK_DATABASE_ID: ${{ secrets.HELPDESK_DATABASE_ID }}
        PROCESSING_STATUS_DATABASE_ID: ${{ secrets.PROCESSING_STATUS_DATABASE_ID }}
